"""Real-history data layer for FinAlly (D1 contract §1) — daily bars.

Three ``HistoryProvider`` implementations feed the ``daily_bars`` SQLite
table (PRIMARY KEY ``(market, ticker, date)``, upserted via INSERT OR
REPLACE):

- :class:`SampleProvider` — reads the committed synthetic CSVs under
  ``app/market/sample_bars/{market}/`` (generated by
  ``scripts/gen_sample_bars.py`` from a fixed seed; NOT real market data).
  Always available: no network, no optional dependency.
- :class:`YFinanceProvider` (us) — Yahoo daily bars via the ``yfinance``
  package with ``auto_adjust=True`` (OHLC arrives already scaled by the
  adj-close ratio, the contract's US 复权 convention).
- :class:`AkshareProvider` (cn) — 东财 ``stock_zh_a_hist(symbol,
  period="daily", adjust="qfq")`` (前复权), with 2 backoff retries.

CORE INVARIANT (contract §0): the real providers import their packages
LAZILY inside the fetch call — a missing/broken ``yfinance``/``akshare``
install or an offline machine degrades to a clear
:class:`HistoryFetchError` ("source unavailable") on sync only. Nothing in
the live market loop, SSE, trading, rules, or strategy paths imports this
module's optional dependencies, and importing :mod:`app.market.history`
itself never touches them. Providers accept an injectable ``fetch_fn`` so
tests exercise every path with fakes — the test suite never performs real
network I/O.

Storage helpers (:func:`upsert_daily_bars`, :func:`sync_daily_bars`,
:func:`load_recent_daily_bars`, :func:`coverage_rows`) operate on an open
sqlite3 connection supplied by the caller; only :func:`sync_daily_bars`
commits (per ticker, so partial progress survives a mid-sync failure).
"""

from __future__ import annotations

import csv
import logging
import math
import time
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Callable, Protocol

logger = logging.getLogger(__name__)

SAMPLE_BARS_DIR = Path(__file__).parent / "sample_bars"

# Approximate trading days per calendar year — used by SampleProvider to map
# a requested (start, end) window onto its fixed-date synthetic series.
TRADING_DAYS_PER_YEAR = 252

# Real (network) provider per market — 'auto' resolves through this map and
# falls back to the sample provider when the real source fails (contract §2).
REAL_SOURCE_BY_MARKET: dict[str, str] = {"us": "yfinance", "cn": "akshare"}


class HistoryFetchError(Exception):
    """A provider could not produce bars — message is user-presentable."""


@dataclass(frozen=True)
class DailyBar:
    """One daily OHLCV bar. ``date`` is an ISO ``YYYY-MM-DD`` string."""

    date: str
    open: float
    high: float
    low: float
    close: float
    volume: float


class HistoryProvider(Protocol):
    """Protocol every history source implements (contract §1)."""

    name: str

    def fetch_daily(self, ticker: str, start: date, end: date) -> list[DailyBar]:
        """Daily bars for ``ticker`` in ``[start, end]``, ascending by date.

        Raises :class:`HistoryFetchError` with a clear, user-presentable
        message on ANY failure (missing dependency, network error, unknown
        ticker, empty result) — never a bare third-party exception.
        """
        ...


# ---------------------------------------------------------------------------
# Sample provider — committed synthetic CSVs, always available
# ---------------------------------------------------------------------------


class SampleProvider:
    """Reads the committed synthetic sample CSVs. Never touches the network.

    The sample series has FIXED dates (it is committed data), so the
    requested ``(start, end)`` window is interpreted as a duration: the
    provider returns the trailing ``(end - start)`` worth of bars
    (~252/year). This keeps ``years=N`` meaningful forever, regardless of
    how far the wall clock drifts past the committed date range.
    """

    name = "sample"

    def __init__(self, market: str, data_dir: Path | None = None) -> None:
        self.market = market
        self._dir = (data_dir or SAMPLE_BARS_DIR) / market

    def fetch_daily(self, ticker: str, start: date, end: date) -> list[DailyBar]:
        symbol = ticker.strip().upper()
        path = self._dir / f"{symbol}.csv"
        if not path.exists():
            raise HistoryFetchError(
                f"No sample data for {symbol} in the '{self.market}' market"
            )
        try:
            with path.open("r", encoding="utf-8", newline="") as fh:
                rows = list(csv.DictReader(fh))
            bars = [
                DailyBar(
                    date=row["date"],
                    open=float(row["open"]),
                    high=float(row["high"]),
                    low=float(row["low"]),
                    close=float(row["close"]),
                    volume=float(row["volume"]),
                )
                for row in rows
            ]
        except (KeyError, TypeError, ValueError, OSError) as exc:
            raise HistoryFetchError(
                f"Sample data for {symbol} is unreadable: {exc}"
            ) from exc
        if not bars:
            raise HistoryFetchError(f"Sample data for {symbol} is empty")
        span_days = max((end - start).days, 1)
        n = max(1, math.ceil(span_days * TRADING_DAYS_PER_YEAR / 365.25))
        return bars[-n:]


# ---------------------------------------------------------------------------
# yfinance provider (us) — lazy import, auto_adjust
# ---------------------------------------------------------------------------


def _import_yfinance():
    """Lazy yfinance import — module-level hook so tests can monkeypatch."""
    import yfinance  # noqa: PLC0415 — deliberate lazy import (contract §1)

    return yfinance


class YFinanceProvider:
    """US daily bars from Yahoo via ``yfinance`` (lazy import).

    ``fetch_fn(ticker, start, end) -> list[DailyBar]`` is injectable for
    tests; the default fetch imports yfinance INSIDE the call and downloads
    with ``auto_adjust=True`` so OHLC comes adj-close scaled (contract §1).
    """

    name = "yfinance"

    def __init__(
        self,
        fetch_fn: Callable[[str, date, date], list[DailyBar]] | None = None,
    ) -> None:
        self._fetch_fn = fetch_fn

    def fetch_daily(self, ticker: str, start: date, end: date) -> list[DailyBar]:
        symbol = ticker.strip().upper()
        fetch = self._fetch_fn or self._default_fetch
        try:
            bars = fetch(symbol, start, end)
        except HistoryFetchError:
            raise
        except Exception as exc:  # third-party errors -> clear message
            raise HistoryFetchError(
                f"yfinance fetch for {symbol} failed: {exc}"
            ) from exc
        if not bars:
            raise HistoryFetchError(
                f"yfinance returned no daily bars for {symbol} — check the "
                "ticker symbol and your network connection"
            )
        return bars

    def _default_fetch(self, symbol: str, start: date, end: date) -> list[DailyBar]:
        try:
            yfinance = _import_yfinance()
        except Exception as exc:
            raise HistoryFetchError(
                "History source 'yfinance' is unavailable — install the "
                f"'yfinance' package to sync US daily bars ({exc})"
            ) from exc
        frame = yfinance.Ticker(symbol).history(
            start=start.isoformat(),
            end=end.isoformat(),
            interval="1d",
            auto_adjust=True,
        )
        bars: list[DailyBar] = []
        for ts, row in frame.iterrows():
            values = [row.get(k) for k in ("Open", "High", "Low", "Close")]
            if any(v is None or v != v for v in values):  # skip NaN rows
                continue
            volume = row.get("Volume")
            bars.append(
                DailyBar(
                    date=ts.date().isoformat(),
                    open=float(values[0]),
                    high=float(values[1]),
                    low=float(values[2]),
                    close=float(values[3]),
                    volume=float(volume) if volume == volume and volume is not None else 0.0,
                )
            )
        bars.sort(key=lambda b: b.date)
        return bars


# ---------------------------------------------------------------------------
# AKShare provider (cn) — 东财 qfq daily bars, lazy import, 2 retries
# ---------------------------------------------------------------------------


def _import_akshare():
    """Lazy akshare import — module-level hook so tests can monkeypatch."""
    import akshare  # noqa: PLC0415 — deliberate lazy import (contract §1)

    return akshare


class AkshareProvider:
    """A-share daily bars via AKShare's 东财 interface (前复权 qfq).

    Retries ``retries`` times with linear backoff (``backoff_seconds``,
    2x, ...) around the injectable ``fetch_fn``; ``sleep`` is injectable so
    tests never wait. Only the 东财 ``stock_zh_a_hist`` endpoint is used
    (contract §1 — the Sina endpoints are deliberately avoided).
    """

    name = "akshare"

    def __init__(
        self,
        fetch_fn: Callable[[str, date, date], list[DailyBar]] | None = None,
        retries: int = 2,
        backoff_seconds: float = 0.8,
        sleep: Callable[[float], None] = time.sleep,
    ) -> None:
        self._fetch_fn = fetch_fn
        self._retries = retries
        self._backoff_seconds = backoff_seconds
        self._sleep = sleep

    def fetch_daily(self, ticker: str, start: date, end: date) -> list[DailyBar]:
        symbol = ticker.strip().upper()
        fetch = self._fetch_fn or self._default_fetch
        attempts = self._retries + 1
        last_error: str = "unknown error"
        for attempt in range(attempts):
            try:
                bars = fetch(symbol, start, end)
                if not bars:
                    raise HistoryFetchError(
                        f"akshare returned no daily bars for {symbol}"
                    )
                return bars
            except HistoryFetchError as exc:
                last_error = str(exc)
            except Exception as exc:
                last_error = str(exc)
            if attempt < attempts - 1:
                self._sleep(self._backoff_seconds * (attempt + 1))
        raise HistoryFetchError(
            f"akshare fetch for {symbol} failed after {attempts} attempts: "
            f"{last_error}"
        )

    def _default_fetch(self, symbol: str, start: date, end: date) -> list[DailyBar]:
        try:
            akshare = _import_akshare()
        except Exception as exc:
            raise HistoryFetchError(
                "History source 'akshare' is unavailable — install the "
                f"'akshare' package to sync A-share daily bars ({exc})"
            ) from exc
        frame = akshare.stock_zh_a_hist(
            symbol=symbol,
            period="daily",
            start_date=start.strftime("%Y%m%d"),
            end_date=end.strftime("%Y%m%d"),
            adjust="qfq",
        )
        bars: list[DailyBar] = []
        for _, row in frame.iterrows():
            bars.append(
                DailyBar(
                    date=str(row["日期"]),
                    open=float(row["开盘"]),
                    high=float(row["最高"]),
                    low=float(row["最低"]),
                    close=float(row["收盘"]),
                    volume=float(row["成交量"]),
                )
            )
        bars.sort(key=lambda b: b.date)
        return bars


def build_default_providers(market: str) -> dict[str, HistoryProvider]:
    """The standard provider set for one market, keyed by source name.

    Construction is cheap and import-free (the real providers import their
    packages lazily inside ``fetch_daily``), so building this at router
    creation can never fail or block startup (contract §0).
    """
    return {
        "sample": SampleProvider(market),
        "yfinance": YFinanceProvider(),
        "akshare": AkshareProvider(),
    }


# ---------------------------------------------------------------------------
# SQLite storage — daily_bars upserts and reads
# ---------------------------------------------------------------------------


def upsert_daily_bars(
    conn,
    *,
    market: str,
    ticker: str,
    bars: list[DailyBar],
    source: str,
    fetched_at: str | None = None,
) -> int:
    """INSERT OR REPLACE one ticker's bars. Does NOT commit; returns count."""
    stamp = fetched_at or datetime.now(timezone.utc).isoformat()
    conn.executemany(
        "INSERT OR REPLACE INTO daily_bars "
        "(market, ticker, date, open, high, low, close, volume, source, fetched_at) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [
            (
                market,
                ticker,
                bar.date,
                float(bar.open),
                float(bar.high),
                float(bar.low),
                float(bar.close),
                float(bar.volume),
                source,
                stamp,
            )
            for bar in bars
        ],
    )
    return len(bars)


def sync_daily_bars(
    conn,
    *,
    market: str,
    tickers: list[str],
    source: str,
    years: int,
    providers: dict[str, HistoryProvider],
    today: date | None = None,
) -> dict:
    """Fetch + upsert daily bars for every ticker (contract §2). Blocking.

    ``source`` is ``'auto'`` or a concrete provider name already validated
    by the route. ``'auto'`` tries the market's real source first and falls
    back to ``sample`` on failure, annotating the fallback row with the real
    source's error message. Per-ticker failures never abort the batch.
    Commits after each ticker so partial progress survives a crash.

    Returns ``{"results": [{ticker, source, bars, error?}, ...],
    "total_bars": int}`` — rows that persisted bars always carry a positive
    ``bars`` and the source that produced them.
    """
    end = today or datetime.now(timezone.utc).date()
    start = end.fromordinal(max(end.toordinal() - round(years * 365.25), 1))

    if source == "auto":
        chain_names = [REAL_SOURCE_BY_MARKET.get(market, "yfinance"), "sample"]
    else:
        chain_names = [source]
    chain = [(name, providers[name]) for name in chain_names if name in providers]

    results: list[dict] = []
    total_bars = 0
    for raw_ticker in tickers:
        ticker = raw_ticker.strip().upper()
        errors: list[str] = []
        outcome: dict | None = None
        for name, provider in chain:
            try:
                bars = provider.fetch_daily(ticker, start, end)
            except HistoryFetchError as exc:
                errors.append(f"{name}: {exc}")
                continue
            except Exception as exc:  # defensive — providers should wrap
                logger.exception("history provider %s crashed for %s", name, ticker)
                errors.append(f"{name}: {exc}")
                continue
            count = upsert_daily_bars(
                conn, market=market, ticker=ticker, bars=bars, source=name
            )
            conn.commit()
            total_bars += count
            outcome = {"ticker": ticker, "source": name, "bars": count}
            # An auto-mode fallback annotates the real source's failure
            # (contract §2: 失败回落 sample 并在响应标注).
            if errors:
                outcome["error"] = "; ".join(errors)
            break
        if outcome is None:
            outcome = {
                "ticker": ticker,
                "source": chain[-1][0] if chain else source,
                "bars": 0,
                "error": "; ".join(errors) or "no provider available",
            }
        results.append(outcome)
    return {"results": results, "total_bars": total_bars}


def load_recent_daily_bars(conn, market: str, ticker: str, limit: int) -> list[dict]:
    """The most recent ``limit`` stored bars, ASCENDING by date.

    Each row: ``{"date", "open", "high", "low", "close", "volume",
    "source"}`` — the history backtest engine and the daily endpoint both
    read this shape.
    """
    rows = conn.execute(
        "SELECT date, open, high, low, close, volume, source FROM daily_bars "
        "WHERE market = ? AND ticker = ? ORDER BY date DESC LIMIT ?",
        (market, ticker, limit),
    ).fetchall()
    return [dict(row) for row in reversed(rows)]


def ticker_coverage(conn, market: str, ticker: str) -> dict:
    """Whole-table coverage for one ticker: ``{from, to, count}``."""
    row = conn.execute(
        "SELECT MIN(date) AS min_date, MAX(date) AS max_date, COUNT(*) AS n "
        "FROM daily_bars WHERE market = ? AND ticker = ?",
        (market, ticker),
    ).fetchone()
    return {"from": row["min_date"], "to": row["max_date"], "count": row["n"]}


def coverage_rows(conn, market: str) -> list[dict]:
    """Per-ticker coverage for one market, ascending by ticker (contract §2).

    ``source`` is the source of the ticker's NEWEST stored bar — the same
    convention the daily endpoint reports.
    """
    rows = conn.execute(
        "SELECT ticker, MIN(date) AS min_date, MAX(date) AS max_date, "
        "COUNT(*) AS n, "
        "(SELECT source FROM daily_bars AS d2 "
        " WHERE d2.market = d.market AND d2.ticker = d.ticker "
        " ORDER BY d2.date DESC LIMIT 1) AS source "
        "FROM daily_bars AS d WHERE market = ? GROUP BY ticker ORDER BY ticker",
        (market,),
    ).fetchall()
    return [
        {
            "ticker": row["ticker"],
            "from": row["min_date"],
            "to": row["max_date"],
            "count": row["n"],
            "source": row["source"],
        }
        for row in rows
    ]
