/**
 * PositionsTable tests (TDD):
 * Test 1: Given a portfolio with one position, all six columns render
 * Test 2: Price update with direction 'up' → current-price cell gains class animate-flash-up;
 *         after 500ms (fake timers) the class is removed
 * Test 3: Empty portfolio → empty-state copy renders
 */
import React from 'react';
import { render, screen, act } from '@testing-library/react';
import { usePriceStore } from '@/stores/priceStore';
import type { PriceUpdate, Position } from '@/types/market';

jest.mock('swr', () => ({
  __esModule: true,
  default: jest.fn(),
}));

import useSWR from 'swr';
const mockUseSWR = useSWR as jest.MockedFunction<typeof useSWR>;

import PositionsTable from '@/components/PositionsTable';

const mockPosition: Position = {
  ticker: 'AAPL',
  quantity: 10,
  avg_cost: 185.5,
  current_price: 188.25,
  unrealized_pnl: 27.5,
  pnl_pct: 1.48,
};

const mockPortfolio = {
  cash: 10000,
  total_value: 11882.5,
  positions: [mockPosition],
};

const mkPrice = (direction: 'up' | 'down' | 'flat', ts = 1717700000): PriceUpdate => ({
  ticker: 'AAPL',
  price: 190.0,
  previous_price: 188.25,
  timestamp: ts,
  change: direction === 'down' ? -1 : 1,
  change_percent: direction === 'down' ? -0.93 : 0.93,
  direction,
});

describe('PositionsTable', () => {
  beforeEach(() => {
    usePriceStore.setState({ prices: {}, connectionStatus: 'disconnected' });
    jest.useFakeTimers();
    mockUseSWR.mockReturnValue({ data: mockPortfolio } as any);
    jest.clearAllMocks();
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  it('Test 1: One position → all six columns render (Ticker, Qty, Avg Cost, Price, P&L, Change %)', () => {
    render(<PositionsTable />);

    // Column headers
    expect(screen.getByText('Ticker')).toBeInTheDocument();
    expect(screen.getByText('Qty')).toBeInTheDocument();
    expect(screen.getByText('Avg Cost')).toBeInTheDocument();
    expect(screen.getByText('Price')).toBeInTheDocument();
    expect(screen.getByText('P&L')).toBeInTheDocument();
    expect(screen.getByText('Change %')).toBeInTheDocument();

    // Row data
    expect(screen.getByText('AAPL')).toBeInTheDocument();
  });

  it('Test 1b: unrealized P&L and % are computed from SWR data when no live price exists', () => {
    render(<PositionsTable />);

    // (188.25 − 185.50) × 10 = +$27.50; 2.75 / 185.50 = +1.48%
    expect(screen.getByText('10')).toBeInTheDocument();
    expect(screen.getByText('$185.50')).toBeInTheDocument();
    expect(screen.getByText('$188.25')).toBeInTheDocument();
    expect(screen.getByText('+$27.50')).toBeInTheDocument();
    expect(screen.getByText('+1.48%')).toBeInTheDocument();
  });

  it('Test 1c: live price from the store overrides SWR price in P&L math', () => {
    render(<PositionsTable />);

    act(() => {
      usePriceStore.setState({ prices: { AAPL: mkPrice('up') } });
    });

    // live 190.00: (190.00 − 185.50) × 10 = +$45.00; 4.50 / 185.50 = +2.43%
    expect(screen.getByText('$190.00')).toBeInTheDocument();
    expect(screen.getByText('+$45.00')).toBeInTheDocument();
    expect(screen.getByText('+2.43%')).toBeInTheDocument();
  });

  it('Test 1d: fractional quantity renders without float residue', () => {
    mockUseSWR.mockReturnValue({
      data: {
        ...mockPortfolio,
        positions: [{ ...mockPosition, quantity: 0.30000000000000004 }],
      },
    } as any);

    render(<PositionsTable />);

    expect(screen.getByText('0.3')).toBeInTheDocument();
    expect(screen.queryByText('0.30000000000000004')).not.toBeInTheDocument();
  });

  it('Test 2: Price update direction up → current-price cell gains animate-flash-up; removed after 500ms', () => {
    const { container } = render(<PositionsTable />);

    // Dispatch a price update with direction 'up'
    act(() => {
      usePriceStore.setState({ prices: { AAPL: mkPrice('up') } });
    });

    // The ref-tracked price cell should have animate-flash-up — these are the
    // Tailwind utilities generated by tailwind.config.js `animation` keys
    // (`flash-up`/`flash-down` → `animate-flash-up`/`animate-flash-down`)
    const priceCells = container.querySelectorAll('[data-price-cell="AAPL"]');
    expect(priceCells.length).toBe(1);
    const priceCell = priceCells[0] as HTMLElement;
    expect(priceCell.classList.contains('animate-flash-up')).toBe(true);
    expect(priceCell.classList.contains('animate-flash-down')).toBe(false);

    // After 500ms, class should be removed
    act(() => {
      jest.advanceTimersByTime(500);
    });
    expect(priceCell.classList.contains('animate-flash-up')).toBe(false);
  });

  it('Test 2b: Price update direction down → current-price cell gains animate-flash-down', () => {
    const { container } = render(<PositionsTable />);

    act(() => {
      usePriceStore.setState({ prices: { AAPL: mkPrice('down') } });
    });

    const priceCell = container.querySelector('[data-price-cell="AAPL"]') as HTMLElement;
    expect(priceCell.classList.contains('animate-flash-down')).toBe(true);
    expect(priceCell.classList.contains('animate-flash-up')).toBe(false);
  });

  it('Test 3: Empty portfolio → empty-state text renders', () => {
    mockUseSWR.mockReturnValue({
      data: { cash: 10000, total_value: 10000, positions: [] },
    } as any);

    render(<PositionsTable />);
    expect(
      screen.getByText('No positions yet. Use the trade bar to buy shares.')
    ).toBeInTheDocument();
  });
});
